kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  kubeProxyMode: "ipvs"
nodes:
  - role: control-plane
    image: &image kindest/node:v1.26.0
    kubeadmConfigPatches: &kubeadmConfigPatches
      - |
        apiVersion: kubeproxy.config.k8s.io/v1alpha1
        kind: KubeProxyConfiguration
        mode: "ipvs"
        ipvs:
          strictARP: true
      - |
        apiVersion: kubelet.config.k8s.io/v1beta1
        kind: KubeletConfiguration
        serverTLSBootstrap: true
  - role: worker
    image: *image
    kubeadmConfigPatches: *kubeadmConfigPatches
  - role: worker
    image: *image
    kubeadmConfigPatches: *kubeadmConfigPatches
