kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  kubeProxyMode: "ipvs"
nodes:
  - role: control-plane
    image: &image kindest/node:v1.23.4
    extraMounts:
      - hostPath: ./data/control-plane
        containerPath: /data
        readOnly: false
        propagation: Bidirectional
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
      - containerPort: 30443
        hostPort: 443
    kubeadmConfigPatches:
      - |
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: InitConfiguration
        nodeRegistration:
          taints:
            []
            # - key: "node-role.kubernetes.io/master"
            #   value: ""
            #   effect: "NoSchedule"
            # - key: "node.cilium.io/agent-not-ready"
            #   value: "true"
            #   effect: "NoSchedule"
      - |
        apiVersion: kubeproxy.config.k8s.io/v1alpha1
        kind: KubeProxyConfiguration
        mode: "ipvs"
        ipvs:
          strictARP: true
      - |
        apiVersion: kubelet.config.k8s.io/v1beta1
        kind: KubeletConfiguration
        serverTLSBootstrap: true
  - role: worker
    image: *image
    extraMounts:
      - hostPath: ./data/worker
        containerPath: /data
        readOnly: false
        propagation: Bidirectional
    kubeadmConfigPatches: &workerPatches
      - |
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: InitConfiguration
        nodeRegistration:
          taints:
            []
            # - key: "node.cilium.io/agent-not-ready"
            #   value: "true"
            #   effect: "NoSchedule"
      - |
        apiVersion: kubeproxy.config.k8s.io/v1alpha1
        kind: KubeProxyConfiguration
        mode: "ipvs"
        ipvs:
          strictARP: true
      - |
        apiVersion: kubelet.config.k8s.io/v1beta1
        kind: KubeletConfiguration
        serverTLSBootstrap: true
  - role: worker
    image: *image
    extraMounts:
      - hostPath: ./data/worker-2
        containerPath: /data
        readOnly: false
        propagation: Bidirectional
    kubeadmConfigPatches: *workerPatches
